from __future__ import annotations

QUEUE_MAX_CONCURRENT_JOBS_MIN = 1
QUEUE_MAX_CONCURRENT_JOBS_MAX = 15
QUEUE_DEFAULT_MAX_CONCURRENT_JOBS = 10

QUEUE_DEFAULT_POLL_SECONDS_MIN = 1
QUEUE_DEFAULT_POLL_SECONDS_MAX = 300
QUEUE_DEFAULT_POLL_SECONDS = 6

QUEUE_MAX_RETRY_ATTEMPTS_MIN = 1
QUEUE_MAX_RETRY_ATTEMPTS_MAX = 10
QUEUE_DEFAULT_MAX_RETRY_ATTEMPTS = 3
