from __future__ import annotations

from typing import List

from .schemas import GraphNodeDefinition, GraphNodeField, GraphNodePort


def prompt_node_definitions() -> List[GraphNodeDefinition]:
    return [
        GraphNodeDefinition(
            type="prompt.text",
            title="Prompt Text",
            description="Reusable text prompt that can feed one or more model prompt inputs.",
            help_text="Type prompt text here or connect upstream text. Replace passes the connected text through; append/prepend combines it with the typed prompt.",
            category="Prompt",
            search_aliases=["prompt", "text", "caption", "description", "input", "pass through"],
            tags=["prompt", "text", "utility"],
            source={"kind": "system"},
            execution={"executor": "prompt.text", "mode": "sync", "cacheable": True, "output_node": False},
            limits={"max_text_chars": 32000},
            ui={
                "default_size": {"width": 340, "height": 320},
                "accent": "purple",
                "icon": "text",
                "connection_dependent_fields": {"mode": "text"},
            },
            ports={
                "inputs": [
                    GraphNodePort(
                        id="text",
                        label="Text",
                        type="text",
                        required=False,
                        max=1,
                        accepts=["text"],
                        description="Optional upstream text from an LLM, concat, or another prompt node.",
                    )
                ],
                "outputs": [GraphNodePort(id="text", label="Text", type="text", description="Final prompt text.")],
            },
            fields=[
                GraphNodeField(
                    id="mode",
                    label="Mode",
                    type="select",
                    required=False,
                    default="replace",
                    options=[
                        {"label": "Replace", "value": "replace"},
                        {"label": "Append", "value": "append"},
                        {"label": "Prepend", "value": "prepend"},
                    ],
                    help_text="How connected text combines with the typed prompt.",
                ),
                GraphNodeField(
                    id="text",
                    label="Prompt",
                    type="textarea",
                    required=False,
                    default="",
                    placeholder="Write a reusable prompt...",
                    connectable=True,
                    port_type="text",
                    help_text="Can be typed directly or driven by a text wire.",
                )
            ],
        ),
        GraphNodeDefinition(
            type="prompt.llm",
            title="LLM Prompt",
            description="Generate or rewrite prompt text with an OpenRouter or local OpenAI-compatible model.",
            help_text="Use text, an optional image, and a system prompt to produce final prompt text. External LLM pricing is reported as unknown until provider pricing is mapped.",
            category="Prompt",
            search_aliases=["llm", "openrouter", "local", "vision", "image describe", "prompt enhance", "gemini", "qwen"],
            tags=["prompt", "text", "llm", "vision"],
            source={
                "kind": "external_llm",
                "providers": ["studio_default", "openrouter", "local_openai"],
                "supports_images": "provider_dependent",
                "pricing": {"status": "unknown_external"},
            },
            execution={"executor": "prompt.llm", "mode": "sync", "cacheable": False, "output_node": False},
            limits={
                "max_user_prompt_chars": 20000,
                "max_system_prompt_chars": 20000,
                "max_image_inputs": 1,
                "max_tokens": {"min": 64, "max": 4000, "default": 1200},
                "temperature": {"min": 0, "max": 2, "default": 0.3},
            },
            ui={
                "default_size": {"width": 420, "height": 720},
                "min_size": {"width": 360, "height": 560},
                "max_size": {"width": 860, "height": 1200},
                "color": "text",
                "accent": "purple",
                "icon": "sparkles",
                "preview": False,
                "field_layout": "stack",
            },
            ports={
                "inputs": [
                    GraphNodePort(
                        id="user_prompt",
                        label="User Prompt",
                        type="text",
                        required=False,
                        max=1,
                        accepts=["text"],
                        description="Optional text to inject into the system prompt or send as the user request.",
                    ),
                    GraphNodePort(
                        id="image",
                        label="Image",
                        type="image",
                        required=False,
                        max=1,
                        accepts=["image"],
                        description="Optional image context. The selected provider model must support image input.",
                    ),
                ],
                "outputs": [
                    GraphNodePort(id="text", label="Text", type="text", description="Generated prompt text."),
                    GraphNodePort(id="metadata", label="Metadata", type="json", advanced=True, description="Provider, model, mode, and safe execution metadata."),
                ],
            },
            fields=[
                GraphNodeField(
                    id="mode",
                    label="Mode",
                    type="select",
                    required=True,
                    default="rewrite_prompt",
                    options=[
                        {"label": "Rewrite Prompt", "value": "rewrite_prompt"},
                        {"label": "Describe Image", "value": "describe_image"},
                        {"label": "Custom", "value": "custom"},
                    ],
                    help_text="Controls the default task sent to the LLM.",
                ),
                GraphNodeField(
                    id="provider",
                    label="Provider",
                    type="select",
                    required=True,
                    default="studio_default",
                    options=[
                        {"label": "Studio Default", "value": "studio_default"},
                        {"label": "OpenRouter", "value": "openrouter"},
                        {"label": "Local OpenAI", "value": "local_openai"},
                    ],
                    help_text="Studio Default uses the saved Media Studio enhancement provider config.",
                ),
                GraphNodeField(
                    id="model_id",
                    label="Model ID",
                    type="text",
                    required=False,
                    default="",
                    placeholder="openai/gpt-4o-mini or local model id",
                    visible_if={"field": "provider", "not_equals": "studio_default"},
                    help_text="Provider model id. Keep this out of workflow secrets; API keys stay in Settings/env.",
                ),
                GraphNodeField(
                    id="model_supports_images",
                    label="Model Supports Images",
                    type="boolean",
                    required=False,
                    default=False,
                    visible_if={"field": "provider", "not_equals": "studio_default"},
                    help_text="Enable only for multimodal model ids when using the image input.",
                ),
                GraphNodeField(
                    id="system_prompt",
                    label="System Prompt",
                    type="textarea",
                    required=True,
                    default="Turn [user_prompt] into a vivid, production-ready image or video prompt. Preserve the core idea and add concrete visual detail.",
                    placeholder="Use [user_prompt] or {user_prompt} where the user text should be injected.",
                    help_text="Supports [user_prompt] or {user_prompt}. If omitted, user text is sent as the user message.",
                ),
                GraphNodeField(
                    id="user_prompt",
                    label="User Prompt",
                    type="textarea",
                    required=False,
                    default="",
                    placeholder="Optional text to rewrite or combine with the system prompt...",
                    connectable=True,
                    port_type="text",
                    help_text="Typed text is used unless a text wire is connected to the User Prompt input.",
                ),
                GraphNodeField(
                    id="image_instruction",
                    label="Image Instruction",
                    type="textarea",
                    required=False,
                    default="Describe the image with subject, composition, lighting, style, and details useful for media generation.",
                    visible_if={"field": "mode", "in": ["describe_image", "custom"]},
                    help_text="Only used when an image is connected.",
                ),
                GraphNodeField(
                    id="temperature",
                    label="Temperature",
                    type="float",
                    required=True,
                    default=0.3,
                    min=0,
                    max=2,
                    help_text="Lower is more deterministic; higher is more varied.",
                ),
                GraphNodeField(
                    id="max_tokens",
                    label="Max Tokens",
                    type="integer",
                    required=True,
                    default=1200,
                    min=64,
                    max=4000,
                    help_text="Upper bound for the generated prompt response.",
                ),
            ],
        ),
        GraphNodeDefinition(
            type="prompt.concat",
            title="Prompt Concat",
            description="Merge multiple prompt text streams into one reusable prompt.",
            category="Prompt",
            search_aliases=["prompt", "concat", "join", "merge", "text"],
            tags=["prompt", "text", "utility"],
            source={"kind": "system"},
            execution={"executor": "prompt.concat", "mode": "sync", "cacheable": True, "output_node": False},
            limits={"max_text_chars": 64000, "max_inputs": 2},
            ui={"default_size": {"width": 300, "height": 260}, "accent": "purple", "icon": "text"},
            ports={
                "inputs": [
                    GraphNodePort(id="text_a", label="Text A", type="text", required=False, max=1, accepts=["text"]),
                    GraphNodePort(id="text_b", label="Text B", type="text", required=False, max=1, accepts=["text"]),
                ],
                "outputs": [GraphNodePort(id="text", label="Text", type="text")],
            },
            fields=[
                GraphNodeField(id="inline_text", label="Inline Text", type="textarea", required=False, default="", placeholder="Optional text to append..."),
                GraphNodeField(id="separator", label="Separator", type="text", required=False, default="\n\n"),
            ],
        ),
    ]
