[program:media-studio-api]
directory=__MEDIA_STUDIO_ROOT__
command=__MEDIA_STUDIO_ROOT__/scripts/start_api.sh
environment=MEDIA_STUDIO_SUPERVISOR="supervisord"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/tmp/media-studio-api.log
stderr_logfile=/tmp/media-studio-api.error.log

[program:media-studio-web]
directory=__MEDIA_STUDIO_ROOT__
command=/usr/bin/env npm run start:web
environment=NODE_ENV="production",PORT="3000",MEDIA_STUDIO_SUPERVISOR="supervisord"
autostart=true
autorestart=true
startsecs=5
stdout_logfile=/tmp/media-studio-web.log
stderr_logfile=/tmp/media-studio-web.error.log
